### ISSUE TITLE
Summarize plants across a set of surveys

### ISSUE THREAD

**Issue by gregorypenn** [gregorypenn/PatricksPlants#2]
**User provides:** a set of surveys/sites, either as a list or all being in the same management unit, or some other criteria.

**Feature should returns:**

- The union set of plants across the sites
- The proportion of sites at which each species occurs

**Comment by aspidoscelis** [comment]
Patrick created functions in allotsum.R and create_PDPs.R that do this.

**Comment by aspidoscelis** [comment]
The first is for adding bits of relevant metadata, the second for pulling a subset and producing the output table.
